-- ---------------------------------------------------------------------------
-- 0014 · Chat con Talento Humano.
--
-- La mayoría de las dudas ("¿cuántos días tengo?", "¿por qué me rechazaron
-- la solicitud?") no justifican un correo ni una llamada, y hoy terminan en
-- WhatsApp personal, fuera de todo registro. Una conversación dentro del
-- sistema deja constancia, llega al equipo de la región y no obliga a nadie
-- a dar su número particular.
--
-- El chat es SOLO entre un colaborador y Talento Humano: no es una red
-- social interna. Un jefe no puede leer lo que su gente consulta, que es
-- justamente lo que haría que nadie preguntara nada.
--
-- Idempotente.
-- ---------------------------------------------------------------------------

create table if not exists public.conversaciones (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references public.users(id) on delete cascade,
  region       text not null default 'sierra' references public.regiones(codigo),
  asunto       text,
  estado       text not null default 'abierta'
               check (estado in ('abierta', 'cerrada')),
  atendida_por uuid references public.users(id) on delete set null,
  cerrada_en   timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists conversaciones_persona_idx
  on public.conversaciones (user_id, updated_at desc);
create index if not exists conversaciones_bandeja_idx
  on public.conversaciones (region, estado, updated_at desc);

create table if not exists public.mensajes (
  id          bigint generated by default as identity primary key,
  conversacion_id uuid not null references public.conversaciones(id) on delete cascade,
  autor_id    uuid not null references public.users(id) on delete cascade,
  es_rrhh     boolean not null default false,
  texto       text not null check (length(btrim(texto)) between 1 and 2000),
  leido_en    timestamptz,
  created_at  timestamptz not null default now()
);

create index if not exists mensajes_conversacion_idx
  on public.mensajes (conversacion_id, created_at);
create index if not exists mensajes_sin_leer_idx
  on public.mensajes (conversacion_id) where leido_en is null;

comment on table public.conversaciones is
  'Consultas de un colaborador a Talento Humano. Llegan al equipo de su región: cualquiera puede responder.';

-- El hilo sube al tope de la bandeja cuando llega un mensaje.
create or replace function public.tg_mensajes_tocar()
returns trigger
language plpgsql
as $tm$
begin
  update public.conversaciones
     set updated_at = now(),
         estado = case when estado = 'cerrada' then 'abierta' else estado end
   where id = new.conversacion_id;
  return new;
end;
$tm$;

drop trigger if exists mensajes_tocar on public.mensajes;
create trigger mensajes_tocar after insert on public.mensajes
  for each row execute function public.tg_mensajes_tocar();

alter table public.conversaciones enable row level security;
alter table public.mensajes enable row level security;

-- Quien consulta ve lo suyo; Talento Humano, lo de su región. El jefe NO:
-- si supiera lo que su gente pregunta, nadie preguntaría.
drop policy if exists conversaciones_visibles on public.conversaciones;
create policy conversaciones_visibles on public.conversaciones
  for select to authenticated
  using (user_id = auth.uid() or is_rrhh_o_admin());

drop policy if exists mensajes_visibles on public.mensajes;
create policy mensajes_visibles on public.mensajes
  for select to authenticated
  using (exists (select 1 from public.conversaciones c
                  where c.id = mensajes.conversacion_id
                    and (c.user_id = auth.uid() or is_rrhh_o_admin())));

-- Realtime: la respuesta aparece sin recargar.
alter table public.mensajes replica identity full;

do $rt$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
     and not exists (select 1 from pg_publication_tables
                      where pubname = 'supabase_realtime'
                        and schemaname = 'public' and tablename = 'mensajes') then
    alter publication supabase_realtime add table public.mensajes;
  end if;
end
$rt$;

create or replace view public.v_conversaciones_bandeja as
select c.id, c.user_id, u.nombre as persona, u.cedula, u.cargo, u.departamento,
       u.ciudad, c.region, c.asunto, c.estado, c.updated_at, c.created_at,
       a.nombre as atendida_por,
       (select count(*) from public.mensajes m
         where m.conversacion_id = c.id and m.leido_en is null and not m.es_rrhh)
         as sin_leer,
       (select m.texto from public.mensajes m
         where m.conversacion_id = c.id order by m.created_at desc limit 1)
         as ultimo_mensaje
  from public.conversaciones c
  join public.users u on u.id = c.user_id
  left join public.users a on a.id = c.atendida_por;

grant select on public.v_conversaciones_bandeja to authenticated;
