-- ---------------------------------------------------------------------------
-- 0025 · El historial de vacaciones que la empresa ya tenía.
--
-- Talento Humano lleva desde hace años una hoja con cada vacación tomada:
-- 3.339 registros de 346 personas, con fecha de inicio, fecha de fin y días
-- gozados. El sistema no tenía nada de eso. Un colaborador entraba, veía su
-- saldo y no podía responder la pregunta más simple que se le ocurre a
-- cualquiera: «¿cuándo tomé vacaciones la última vez?».
--
-- Estos registros NO son solicitudes de este sistema, y por eso no van a
-- `requests`. Nunca pasaron por un jefe, no tienen folio, ni código QR, ni
-- quién las autorizó: son lo que la empresa anotó en una hoja de cálculo.
-- Meterlas en `requests` habría sido inventar un trámite que no ocurrió, y
-- además habría disparado todas las reglas —anticipación, bloques, solape—
-- sobre hechos de 2018 que no tienen por qué cumplirlas.
--
-- Tampoco tocan el saldo. El saldo de cada persona ya está cargado desde la
-- misma hoja y es correcto; lo que faltaba era el detalle de cómo se llegó a
-- él. Sumar estos días otra vez sería descontarlos dos veces.
--
-- Idempotente: cargar el mismo archivo dos veces no duplica nada.
-- ---------------------------------------------------------------------------

create table if not exists public.vacaciones_historicas (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references public.users(id) on delete cascade,
  fecha_inicio  date not null,
  fecha_fin     date not null,
  dias          numeric(6,2) not null check (dias > 0),
  -- De dónde salió el dato. Hoy solo hay un origen, pero el día que alguien
  -- cargue otra planilla conviene poder distinguirlas sin adivinar.
  origen        text not null default 'hoja_talento_humano',
  -- La fila exacta del archivo. Es lo que permite volver al papel cuando
  -- alguien discute un dato: «fila 1.847 de la hoja que cargó Talento
  -- Humano» es una respuesta; «lo dice el sistema» no lo es.
  fila_origen   integer,
  cargado_en    timestamptz not null default now(),
  cargado_por   uuid references public.users(id) on delete set null,
  constraint historicas_rango check (fecha_fin >= fecha_inicio),
  -- Cargar el mismo archivo dos veces no duplica: una persona no tomó dos
  -- veces vacaciones exactamente las mismas fechas.
  constraint historicas_sin_repetir unique (user_id, fecha_inicio, fecha_fin)
);

create index if not exists historicas_usuario_idx
  on public.vacaciones_historicas (user_id, fecha_inicio desc);

comment on table public.vacaciones_historicas is
  'Vacaciones tomadas antes de este sistema, tal como las anotó Talento Humano en su hoja. No son solicitudes: no tienen folio ni aprobación, y no tocan el saldo, que ya viene cargado de la misma fuente.';

alter table public.vacaciones_historicas enable row level security;

drop policy if exists historicas_propias on public.vacaciones_historicas;
create policy historicas_propias on public.vacaciones_historicas
  for select to authenticated
  using (user_id = auth.uid() or is_rrhh_o_admin());

-- =========================================================================
-- El historial completo: lo de antes y lo de ahora, en una sola línea de
-- tiempo y diciendo de dónde viene cada cosa.
--
-- Mezclarlas sin decirlo sería el error que hay que evitar: una persona que
-- ve «15 días en marzo de 2019» tiene derecho a saber si eso lo tramitó por
-- aquí o si viene de la hoja que llevaba Talento Humano.
-- =========================================================================

create or replace view public.v_historial_vacaciones as
select h.user_id,
       null::bigint          as folio,
       h.fecha_inicio,
       h.fecha_fin,
       h.dias,
       'historico'::text     as procedencia,
       'Registrado por Talento Humano antes de este sistema'::text as detalle,
       h.fila_origen
  from public.vacaciones_historicas h
union all
select r.user_id,
       r.folio,
       r.fecha_inicio,
       r.fecha_fin,
       r.dias_solicitados as dias,
       'solicitud'::text  as procedencia,
       'Solicitada y autorizada en el sistema'::text as detalle,
       null::integer
  from public.requests r
 where r.tipo = 'vacacion' and r.estado = 'aprobado';

grant select on public.v_historial_vacaciones to authenticated;

comment on view public.v_historial_vacaciones is
  'Todas las vacaciones de una persona, de antes y de ahora, diciendo de dónde viene cada registro. Nunca se presentan mezcladas sin distinguir.';

-- Lo que la hoja dice que cada quien gozó, para poder cotejarlo.
create or replace view public.v_historico_resumen as
select u.id as user_id, u.cedula, u.nombre, u.departamento,
       count(h.id)                      as vacaciones_registradas,
       coalesce(sum(h.dias), 0)         as dias_gozados_historicos,
       min(h.fecha_inicio)              as primera,
       max(h.fecha_fin)                 as ultima,
       u.dias_vacaciones                as saldo_actual
  from public.users u
  left join public.vacaciones_historicas h on h.user_id = u.id
 where u.activo
 group by u.id, u.cedula, u.nombre, u.departamento, u.dias_vacaciones
 order by u.nombre;

grant select on public.v_historico_resumen to authenticated;
