-- ---------------------------------------------------------------------------
-- 0007 · Pilares de permisos, guías de redacción, bloque mínimo de vacaciones,
--        reemplazo asignado por jefatura y ajustes de Talento Humano.
--
-- Idempotente: puede ejecutarse varias veces. Cada sentencia es independiente,
-- de modo que el editor SQL de Supabase pueda aplicarlas por partes.
-- ---------------------------------------------------------------------------

-- =========================================================================
-- A. Tres pilares de permiso
--
-- El colaborador elige primero el pilar y después el subtipo. Reduce 16
-- opciones planas —que obligaban a leerlas todas— a tres preguntas claras:
-- ¿es una emergencia del hogar, es salud, o es un asunto propio?
-- =========================================================================

create table if not exists public.permission_categories (
  id          smallint generated by default as identity primary key,
  codigo      text not null unique,
  nombre      text not null,
  descripcion text not null,
  ayuda       text,
  orden       integer not null default 100,
  activo      boolean not null default true,
  created_at  timestamptz not null default now()
);

alter table public.permission_categories enable row level security;

drop policy if exists permission_categories_lectura on public.permission_categories;
create policy permission_categories_lectura on public.permission_categories
  for select to authenticated using (true);

insert into public.permission_categories (codigo, nombre, descripcion, ayuda, orden) values
  ('calamidad_domestica', 'Calamidad doméstica',
   'Hecho grave e imprevisto en su entorno familiar o su vivienda que exige su presencia inmediata.',
   'Son situaciones que usted no pudo prever ni evitar. Código del Trabajo, Art. 42 núm. 30.',
   10),
  ('cita_medica', 'Cita médica',
   'Atención de salud suya o de quien depende de usted, incluidas las licencias que la ley reconoce.',
   'Cubre desde una consulta de una hora hasta un reposo con certificado. Código del Trabajo, Art. 42 núm. 9.',
   20),
  ('permiso_personal', 'Permiso personal',
   'Obligaciones legales, trámites y asuntos propios que solo pueden atenderse en horario laboral.',
   'Si el trámite puede hacerse fuera del horario, no corresponde este permiso.',
   30)
on conflict (codigo) do update
  set nombre = excluded.nombre,
      descripcion = excluded.descripcion,
      ayuda = excluded.ayuda,
      orden = excluded.orden;

-- =========================================================================
-- B. Los subtipos cuelgan de un pilar y traen guía de redacción
--
-- `guia_ejemplo` es el ejemplo que se muestra bajo el campo de descripción.
-- `guia_adjuntos` dice qué respaldo espera quien va a decidir. Ambos se
-- muestran al elegir el subtipo: nadie debería adivinar qué escribir.
-- =========================================================================

alter table public.permission_types
  add column if not exists category_id smallint references public.permission_categories(id);
alter table public.permission_types add column if not exists guia_ejemplo text;
alter table public.permission_types add column if not exists guia_adjuntos text;

create index if not exists permission_types_categoria_idx
  on public.permission_types (category_id, orden) where activo;

-- Tres subtipos que faltaban y que en la práctica se usan constantemente.
insert into public.permission_types
  (codigo, nombre, descripcion, requiere_adjunto, remunerado, max_dias, max_horas, legal_ref, orden)
values
  ('emergencia_medica', 'Emergencia médica propia',
   'Atención imprevista en emergencia, sin cita previa', true, true, null, null, 'CT_ART_42_9', 15),
  ('acompanamiento_medico', 'Acompañamiento a cita médica de familiar',
   'Acompañar a un familiar dependiente a su atención de salud', true, true, 1, 8, 'CT_ART_42_9', 25),
  ('enfermedad_familiar', 'Enfermedad grave o accidente de familiar',
   'Emergencia de salud de un familiar cercano que exige su presencia', true, true, 3, null, 'CT_ART_42_30', 35)
on conflict (codigo) do nothing;

insert into public.permission_types
  (codigo, nombre, descripcion, requiere_adjunto, remunerado, max_dias, legal_ref, orden)
values
  ('siniestro_domicilio', 'Siniestro en la vivienda',
   'Incendio, inundación, robo u otro daño grave en su domicilio', true, true, 2, 'CT_ART_42_30', 36)
on conflict (codigo) do nothing;

-- ------------------------------------------------- asignación a cada pilar
update public.permission_types t set category_id = c.id
  from public.permission_categories c
 where c.codigo = 'calamidad_domestica'
   and t.codigo in ('fallecimiento_familiar', 'enfermedad_familiar',
                    'siniestro_domicilio', 'caso_fortuito');

update public.permission_types t set category_id = c.id
  from public.permission_categories c
 where c.codigo = 'cita_medica'
   and t.codigo in ('cita_medica', 'emergencia_medica', 'enfermedad', 'maternidad',
                    'paternidad', 'lactancia', 'cuidado_discapacidad',
                    'donacion_sangre', 'acompanamiento_medico');

update public.permission_types t set category_id = c.id
  from public.permission_categories c
 where c.codigo = 'permiso_personal'
   and t.codigo in ('citacion_judicial', 'tramite_gobierno', 'sufragio',
                    'estudios', 'matrimonio', 'permiso_personal');

-- Ningún subtipo puede quedar huérfano: si alguno no encajó, va a personal.
update public.permission_types t set category_id = c.id
  from public.permission_categories c
 where c.codigo = 'permiso_personal' and t.category_id is null;

-- ------------------------------------------------- guías de redacción
-- Quien decide (jefe y Talento Humano) solo cuenta con lo que el solicitante
-- escriba. Un ejemplo concreto por subtipo evita el clásico «permiso
-- personal» sin más, que obliga a devolver la solicitud y perder un día.

update public.permission_types set
  guia_ejemplo = 'Ej.: Tengo cita de control con el traumatólogo en el Hospital de los Valles, av. Interoceánica. La cita es a las 10:00. Salgo 09:00 y calculo volver a las 12:30 porque voy en transporte público.',
  guia_adjuntos = 'Adjunte la captura o el documento del turno donde se lean la fecha, la hora y el establecimiento.'
where codigo = 'cita_medica';

update public.permission_types set
  guia_ejemplo = 'Ej.: Me descompensé en la oficina con dolor en el pecho y acudí a emergencias del Hospital Metropolitano a las 11:20. Aviso desde la sala de espera e informaré el diagnóstico apenas me atiendan.',
  guia_adjuntos = 'Hoja de atención de emergencia o el certificado que emita el establecimiento. Si aún no lo tiene, entréguelo al reincorporarse.'
where codigo = 'emergencia_medica';

update public.permission_types set
  guia_ejemplo = 'Ej.: El médico del IESS me otorgó reposo por 3 días, del 12 al 14 de marzo, por un cuadro de gastroenteritis. Me reincorporo el 15 a primera hora.',
  guia_adjuntos = 'Certificado de reposo del IESS o del médico tratante, con sello y número de registro profesional.'
where codigo = 'enfermedad';

update public.permission_types set
  guia_ejemplo = 'Ej.: Debo acompañar a mi hijo de 6 años a su control pediátrico en el Centro de Salud de Cotocollao. La cita es a las 08:30 y calculo estar en la oficina a las 11:00.',
  guia_adjuntos = 'Turno de la cita del familiar y un documento que acredite el parentesco.'
where codigo = 'acompanamiento_medico';

update public.permission_types set
  guia_ejemplo = 'Ej.: Mi fecha probable de parto es el 20 de mayo. Solicito las 12 semanas de licencia desde esa fecha. Dejé al día el informe mensual y coordiné el traspaso con mi equipo.',
  guia_adjuntos = 'Certificado médico con la fecha probable de parto. Tras el nacimiento, la partida de nacimiento o el certificado de nacido vivo.'
where codigo = 'maternidad';

update public.permission_types set
  guia_ejemplo = 'Ej.: Mi hija nació el 3 de abril en la Clínica Pichincha. Solicito los días de licencia desde el 4 de abril.',
  guia_adjuntos = 'Certificado de nacido vivo o partida de nacimiento.'
where codigo = 'paternidad';

update public.permission_types set
  guia_ejemplo = 'Ej.: Me reincorporo el 1 de julio y solicito la jornada reducida por lactancia hasta que mi hijo cumpla 12 meses. Entraré a las 08:00 y saldré a las 14:00.',
  guia_adjuntos = 'Partida de nacimiento del menor.'
where codigo = 'lactancia';

update public.permission_types set
  guia_ejemplo = 'Ej.: Mi madre tiene discapacidad del 60% y debo llevarla a su terapia en la av. América. La cita es a las 15:00 y calculo 2 horas.',
  guia_adjuntos = 'Carné de discapacidad del familiar y el turno o cita a la que asistirá.'
where codigo = 'cuidado_discapacidad';

update public.permission_types set
  guia_ejemplo = 'Ej.: Donaré sangre en la Cruz Roja de la av. Gran Colombia por un pedido para mi cuñado, internado en el Eugenio Espejo. Voy a las 09:00 y calculo regresar a las 12:00.',
  guia_adjuntos = 'Comprobante de la donación emitido por la Cruz Roja o el banco de sangre. Puede entregarlo al volver.'
where codigo = 'donacion_sangre';

update public.permission_types set
  guia_ejemplo = 'Ej.: Falleció mi padre el 8 de marzo en Ambato. Viajo hoy para el velorio y el sepelio, y regreso el 11 de marzo.',
  guia_adjuntos = 'Certificado o acta de defunción. Si aún no lo tiene, entréguelo al reincorporarse.'
where codigo = 'fallecimiento_familiar';

update public.permission_types set
  guia_ejemplo = 'Ej.: Mi esposa sufrió un accidente de tránsito y está internada en el Hospital Vozandes. Debo acompañarla hoy y mañana porque no hay otro familiar en la ciudad.',
  guia_adjuntos = 'Hoja de atención, certificado del hospital o parte policial del accidente.'
where codigo = 'enfermedad_familiar';

update public.permission_types set
  guia_ejemplo = 'Ej.: Se rompió la tubería matriz y se inundó mi departamento en Carcelén. Debo estar presente para el plomero y el peritaje del seguro. Calculo el día completo.',
  guia_adjuntos = 'Fotografías del daño y, según el caso, parte de bomberos, denuncia o informe del seguro.'
where codigo = 'siniestro_domicilio';

update public.permission_types set
  guia_ejemplo = 'Ej.: Un deslave cerró la vía a Nono desde las 06:00 y no hay paso vehicular. Estoy retenido en el km 12 y adjunto la publicación del ECU-911. Llegaré apenas se habilite la vía.',
  guia_adjuntos = 'Cualquier constancia del hecho: publicación oficial, parte policial o fotografía con fecha.'
where codigo = 'caso_fortuito';

update public.permission_types set
  guia_ejemplo = 'Ej.: Tengo citación de la Agencia Nacional de Tránsito para impugnar una multa que considero sin fundamento. La diligencia es a las 10:00 en la agencia de la av. Occidental. Voy en transporte público, así que calculo entre 1 y 2 horas fuera de la oficina.',
  guia_adjuntos = 'La boleta de citación o notificación, y el documento del caso: la multa, el expediente o las fotografías que respalden su posición.'
where codigo = 'citacion_judicial';

update public.permission_types set
  guia_ejemplo = 'Ej.: Debo renovar mi cédula en el Registro Civil del CCI. El turno es a las 08:00 del martes 5 y es el único disponible este mes. Calculo 2 horas.',
  guia_adjuntos = 'El turno o la cita agendada, donde se lean la fecha, la hora y la institución.'
where codigo = 'tramite_gobierno';

update public.permission_types set
  guia_ejemplo = 'Ej.: Soy miembro de la junta receptora del voto en el recinto Colegio Mejía para las elecciones del 9 de febrero.',
  guia_adjuntos = 'Notificación como miembro de junta o certificado de votación. Puede entregarlo después.'
where codigo = 'sufragio';

update public.permission_types set
  guia_ejemplo = 'Ej.: Rindo el examen final de la maestría en la PUCE el jueves 12, de 18:00 a 20:00, y necesito salir a las 17:00. Es la única fecha: la supletoria es en dos meses.',
  guia_adjuntos = 'Calendario académico, convocatoria al examen o certificado de la institución.'
where codigo = 'estudios';

update public.permission_types set
  guia_ejemplo = 'Ej.: Me caso el 14 de junio en el Registro Civil de la av. Amazonas, a las 11:00. Solicito ese día y los dos siguientes.',
  guia_adjuntos = 'Certificado de matrimonio o la constancia del turno en el Registro Civil.'
where codigo = 'matrimonio';

update public.permission_types set
  guia_ejemplo = 'Ej.: Necesito la mañana del viernes 7 para un asunto familiar en Sangolquí. Entiendo que se descuenta de mi saldo de vacaciones. Regreso a las 14:00.',
  guia_adjuntos = 'No exige respaldo, pero adjunte lo que ayude a su jefe a dimensionar la urgencia.'
where codigo = 'permiso_personal';

-- El antiguo tipo genérico «Calamidad doméstica» pasó a ser un pilar. No se
-- elimina —hay solicitudes que lo referencian y la bitácora es inmutable—:
-- se convierte en el subtipo de respaldo para lo que no encaje en los otros.
update public.permission_types set
  nombre = 'Otra calamidad doméstica',
  descripcion = 'Hecho grave e imprevisto del hogar que no encaja en los anteriores',
  orden = 39,
  guia_ejemplo = 'Ej.: Mi hija de 8 años se quedó sola porque la persona que la cuida sufrió una emergencia y debo retirarla de la escuela en La Floresta a las 13:00. No tengo con quién dejarla el resto de la tarde.',
  guia_adjuntos = 'Adjunte lo que documente el hecho. Si no existe documento, explique con el mayor detalle posible: es lo único con lo que contará quien decida.'
where codigo = 'calamidad_domestica';

update public.permission_types t set category_id = c.id
  from public.permission_categories c
 where c.codigo = 'calamidad_domestica' and t.codigo = 'calamidad_domestica';

-- Orden dentro de cada pilar: de lo más frecuente a lo más excepcional, y el
-- subtipo de respaldo siempre al final.
update public.permission_types set orden = 31 where codigo = 'fallecimiento_familiar';
update public.permission_types set orden = 32 where codigo = 'enfermedad_familiar';
update public.permission_types set orden = 33 where codigo = 'siniestro_domicilio';
update public.permission_types set orden = 34 where codigo = 'caso_fortuito';
update public.permission_types set orden = 39 where codigo = 'calamidad_domestica';

-- =========================================================================
-- C. Bloque mínimo de vacaciones
--
-- Regla de la empresa: las vacaciones se toman en bloques de al menos 7 días
-- calendario. Pedir menos deja de ser un trámite ordinario y pasa a ser una
-- excepción: exige documento y justificación, y se decide en orden inverso
-- —primero Talento Humano, después el jefe inmediato—, porque quien autoriza
-- apartarse de la política es Talento Humano, no la jefatura.
-- =========================================================================

insert into public.app_config (clave, valor, descripcion) values
  ('vacaciones_bloque_minimo', '7',
   'Días calendario mínimos por solicitud de vacaciones. Menos exige justificación documentada y lo autoriza primero Talento Humano.')
on conflict (clave) do update set descripcion = excluded.descripcion;

insert into public.app_config (clave, valor, descripcion) values
  ('mandato_descripcion',
   'Declare toda la información pertinente: el motivo, el lugar, la hora y cuánto tiempo estará ausente. Su jefe inmediato y Talento Humano deciden únicamente con lo que usted escriba aquí y con lo que adjunte. Si falta un dato, la solicitud se devuelve y usted pierde el tiempo que quería ganar.',
   'Texto que encabeza el campo de descripción en toda solicitud')
on conflict (clave) do update set valor = excluded.valor, descripcion = excluded.descripcion;

alter table public.requests
  add column if not exists ruta_aprobacion text not null default 'estandar';

alter table public.requests
  add column if not exists bloque_menor_justificado boolean not null default false;

do $ruta$
begin
  if not exists (select 1 from pg_constraint where conname = 'requests_ruta_aprobacion_valida') then
    alter table public.requests add constraint requests_ruta_aprobacion_valida
      check (ruta_aprobacion in ('estandar', 'rrhh_primero'));
  end if;
end
$ruta$;

comment on column public.requests.ruta_aprobacion is
  'estandar: jefe y luego Talento Humano. rrhh_primero: excepción a una regla de política, la autoriza Talento Humano antes que la jefatura.';

-- =========================================================================
-- D. Ajustes de Talento Humano sobre lo ya otorgado
--
-- Caso real: se autoriza un permiso de 2 horas por cita médica y de ahí sale
-- un reposo de 3 días. Hasta ahora el sistema solo conocía el permiso
-- original: garita seguía esperando a la persona y el jefe la daba por
-- presente. Talento Humano puede ahora extender o reducir la ausencia,
-- dejando constancia de por qué.
--
-- No se pisa el historial: la solicitud conserva sus fechas originales en
-- esta tabla, y cada ajuste queda con autor, momento y justificación.
-- =========================================================================

create table if not exists public.request_adjustments (
  id                bigint generated by default as identity primary key,
  request_id        uuid not null references public.requests(id) on delete cascade,
  fecha_inicio_ant  date not null,
  fecha_fin_ant     date not null,
  fecha_inicio_nueva date not null,
  fecha_fin_nueva   date not null,
  dias_ant          numeric(6,2) not null,
  dias_nuevos       numeric(6,2) not null,
  motivo            text not null,
  resolucion        text not null,
  ajustado_por      uuid not null references public.users(id),
  created_at        timestamptz not null default now(),
  constraint request_adjustments_rango_valido check (fecha_fin_nueva >= fecha_inicio_nueva),
  constraint request_adjustments_motivo_util check (length(btrim(motivo)) >= 15),
  constraint request_adjustments_resolucion_util check (length(btrim(resolucion)) >= 15)
);

comment on table public.request_adjustments is
  'Extensiones y correcciones que Talento Humano aplica a una ausencia ya autorizada. Inmutable: solo se inserta.';

create index if not exists request_adjustments_request_idx
  on public.request_adjustments (request_id, created_at desc);

alter table public.request_adjustments enable row level security;

-- El interesado ve los ajustes de sus propias ausencias; Talento Humano y el
-- jefe inmediato, los de quienes deben cubrir. Nadie puede editarlos.
drop policy if exists request_adjustments_lectura on public.request_adjustments;
create policy request_adjustments_lectura on public.request_adjustments
  for select to authenticated using (
    is_rrhh_o_admin()
    or exists (
      select 1 from public.requests r
       where r.id = request_adjustments.request_id
         and (r.user_id = auth.uid() or r.jefe_id = auth.uid())
    )
  );

drop policy if exists request_adjustments_sin_edicion on public.request_adjustments;
create policy request_adjustments_sin_edicion on public.request_adjustments
  for update to authenticated using (false);

-- Marca en la solicitud para que garita, informes y calendario distingan una
-- ausencia ajustada de una original sin tener que cruzar tablas.
alter table public.requests add column if not exists ajustada_en timestamptz;
alter table public.requests add column if not exists ajustada_por uuid references public.users(id);

-- ------------------------------------------------- aplicación del ajuste
-- Todo en una función para que el saldo, las fechas y la constancia se
-- muevan juntos o no se muevan: si el ajuste sobre una vacación cambia los
-- días, hay que devolver los anteriores y descontar los nuevos, y eso no
-- puede quedar a medias.
create or replace function public.ajustar_ausencia(
  p_request_id uuid,
  p_inicio     date,
  p_fin        date,
  p_motivo     text,
  p_resolucion text,
  p_por        uuid
) returns public.requests
language plpgsql
security definer
set search_path = public
as $ajuste$
declare
  v_sol    public.requests;
  v_dias   numeric(6,2);
  v_fds    integer;
begin
  select * into v_sol from public.requests where id = p_request_id for update;
  if not found then
    raise exception 'La solicitud no existe';
  end if;

  if v_sol.estado <> 'aprobado' then
    raise exception 'Solo se ajusta una ausencia ya aprobada (esta está en %)', v_sol.estado;
  end if;

  if p_fin < p_inicio then
    raise exception 'La fecha de fin no puede ser anterior a la de inicio';
  end if;

  if length(btrim(coalesce(p_motivo, ''))) < 15 or length(btrim(coalesce(p_resolucion, ''))) < 15 then
    raise exception 'El ajuste exige explicar el caso y la resolución (mínimo 15 caracteres cada uno)';
  end if;

  v_dias := public.calcular_dias(v_sol.tipo, p_inicio, p_fin);

  -- El saldo solo se mueve en vacaciones; un permiso remunerado no lo toca.
  if v_sol.tipo = 'vacacion' and v_dias <> v_sol.dias_solicitados then
    perform public.reversar_vacaciones(v_sol.user_id, v_sol.dias_solicitados,
                                       v_sol.id, v_sol.fines_semana);
    v_fds := v_sol.fines_semana;
    perform public.consumir_vacaciones(v_sol.user_id, v_dias, v_sol.id, v_fds, p_por);
  end if;

  insert into public.request_adjustments
    (request_id, fecha_inicio_ant, fecha_fin_ant, fecha_inicio_nueva, fecha_fin_nueva,
     dias_ant, dias_nuevos, motivo, resolucion, ajustado_por)
  values
    (v_sol.id, v_sol.fecha_inicio, v_sol.fecha_fin, p_inicio, p_fin,
     v_sol.dias_solicitados, v_dias, btrim(p_motivo), btrim(p_resolucion), p_por);

  update public.requests set
    fecha_inicio = p_inicio,
    fecha_fin = p_fin,
    dias_solicitados = v_dias,
    ajustada_en = now(),
    ajustada_por = p_por,
    updated_at = now()
  where id = v_sol.id
  returning * into v_sol;

  return v_sol;
end
$ajuste$;

revoke all on function public.ajustar_ausencia(uuid, date, date, text, text, uuid) from public;

-- =========================================================================
-- E. Calendario de jefatura
--
-- El jefe necesita ver a su equipo mes a mes para no quedarse sin nadie. Se
-- añade lo que le sirve para planificar —si es media jornada o la semana
-- entera, quién cubre, si Talento Humano ya lo ajustó— y se sigue omitiendo
-- el motivo detallado: el subtipo de un permiso médico es dato de salud
-- (LOPDP Art. 4). El jefe lo ve en la solicitud que él mismo autoriza, que
-- es donde corresponde, no en una grilla mensual a la vista de todos.
-- =========================================================================

-- Se recrea en vez de reemplazarse: se añaden columnas en medio (cargo,
-- horas, tipo) y PostgreSQL no permite renombrar columnas con
-- `create or replace view`.
drop view if exists public.v_calendario_equipo;

create view public.v_calendario_equipo as
select r.id            as request_id,
       r.folio,
       u.id            as user_id,
       u.nombre,
       u.cargo,
       u.departamento,
       u.jefe_id,
       r.fecha_inicio,
       r.fecha_fin,
       r.hora_inicio,
       r.hora_fin,
       r.dias_solicitados,
       r.estado,
       r.tipo,
       case r.tipo when 'vacacion' then 'Vacaciones' else 'Permiso' end as motivo_general,
       r.reemplazo_id,
       s.nombre        as reemplazo_nombre,
       r.ajustada_en
  from public.requests r
  join public.users u on u.id = r.user_id
  left join public.users s on s.id = r.reemplazo_id
 where r.estado in ('pendiente_jefe', 'pendiente_rrhh', 'pendiente_anulacion', 'aprobado')
   and r.fecha_fin >= current_date - 31;

comment on view public.v_calendario_equipo is
  'Ausencias vigentes para planificar cobertura. Nunca expone el subtipo del permiso: es dato de salud bajo LOPDP Art. 4.';

grant select on public.v_calendario_equipo to authenticated;

-- Catálogo que consume el formulario: pilar, subtipos y guías en una consulta.
create or replace view public.v_catalogo_permisos as
select c.id          as categoria_id,
       c.codigo      as categoria_codigo,
       c.nombre      as categoria_nombre,
       c.descripcion as categoria_descripcion,
       c.ayuda       as categoria_ayuda,
       c.orden       as categoria_orden,
       t.id          as tipo_id,
       t.codigo      as tipo_codigo,
       t.nombre      as tipo_nombre,
       t.descripcion as tipo_descripcion,
       t.requiere_adjunto,
       t.requiere_justificacion,
       t.remunerado,
       t.descuenta_vacaciones,
       t.max_dias,
       t.max_horas,
       t.legal_ref,
       t.guia_ejemplo,
       t.guia_adjuntos,
       t.orden       as tipo_orden
  from public.permission_categories c
  join public.permission_types t on t.category_id = c.id
 where c.activo and t.activo;

grant select on public.v_catalogo_permisos to authenticated;
