-- ---------------------------------------------------------------------------
-- 0007 · Pilares de permisos, guías de redacción, bloque mínimo de vacaciones,
--        reemplazo asignado por jefatura y ajustes de Talento Humano.
--
-- Idempotente: puede ejecutarse varias veces. Cada sentencia es independiente,
-- de modo que el editor SQL de Supabase pueda aplicarlas por partes.
-- ---------------------------------------------------------------------------

-- =========================================================================
-- A. Tres pilares de permiso
--
-- El colaborador elige primero el pilar y después el subtipo. Reduce 16
-- opciones planas —que obligaban a leerlas todas— a tres preguntas claras:
-- ¿es una emergencia del hogar, es salud, o es un asunto propio?
-- =========================================================================

create table if not exists public.permission_categories (
  id          smallint generated by default as identity primary key,
  codigo      text not null unique,
  nombre      text not null,
  descripcion text not null,
  ayuda       text,
  orden       integer not null default 100,
  activo      boolean not null default true,
  created_at  timestamptz not null default now()
);

alter table public.permission_categories enable row level security;

drop policy if exists permission_categories_lectura on public.permission_categories;
create policy permission_categories_lectura on public.permission_categories
  for select to authenticated using (true);

insert into public.permission_categories (codigo, nombre, descripcion, ayuda, orden) values
  ('calamidad_domestica', 'Calamidad doméstica',
   'Hecho grave e imprevisto en su entorno familiar o su vivienda que exige su presencia inmediata.',
   'Son situaciones que usted no pudo prever ni evitar. Código del Trabajo, Art. 42 núm. 30.',
   10),
  ('cita_medica', 'Cita médica',
   'Atención de salud suya o de quien depende de usted, incluidas las licencias que la ley reconoce.',
   'Cubre desde una consulta de una hora hasta un reposo con certificado. Código del Trabajo, Art. 42 núm. 9.',
   20),
  ('permiso_personal', 'Permiso personal',
   'Obligaciones legales, trámites y asuntos propios que solo pueden atenderse en horario laboral.',
   'Si el trámite puede hacerse fuera del horario, no corresponde este permiso.',
   30)
on conflict (codigo) do update
  set nombre = excluded.nombre,
      descripcion = excluded.descripcion,
      ayuda = excluded.ayuda,
      orden = excluded.orden;

-- =========================================================================
-- B. Los subtipos cuelgan de un pilar y traen guía de redacción
--
-- `guia_ejemplo` es el ejemplo que se muestra bajo el campo de descripción.
-- `guia_adjuntos` dice qué respaldo espera quien va a decidir. Ambos se
-- muestran al elegir el subtipo: nadie debería adivinar qué escribir.
-- =========================================================================

alter table public.permission_types
  add column if not exists category_id smallint references public.permission_categories(id);
alter table public.permission_types add column if not exists guia_ejemplo text;
alter table public.permission_types add column if not exists guia_adjuntos text;

create index if not exists permission_types_categoria_idx
  on public.permission_types (category_id, orden) where activo;

-- Tres subtipos que faltaban y que en la práctica se usan constantemente.
insert into public.permission_types
  (codigo, nombre, descripcion, requiere_adjunto, remunerado, max_dias, max_horas, legal_ref, orden)
values
  ('emergencia_medica', 'Emergencia médica propia',
   'Atención imprevista en emergencia, sin cita previa', true, true, null, null, 'CT_ART_42_9', 15),
  ('acompanamiento_medico', 'Acompañamiento a cita médica de familiar',
   'Acompañar a un familiar dependiente a su atención de salud', true, true, 1, 8, 'CT_ART_42_9', 25),
  ('enfermedad_familiar', 'Enfermedad grave o accidente de familiar',
   'Emergencia de salud de un familiar cercano que exige su presencia', true, true, 3, null, 'CT_ART_42_30', 35)
on conflict (codigo) do nothing;

insert into public.permission_types
  (codigo, nombre, descripcion, requiere_adjunto, remunerado, max_dias, legal_ref, orden)
values
  ('siniestro_domicilio', 'Siniestro en la vivienda',
   'Incendio, inundación, robo u otro daño grave en su domicilio', true, true, 2, 'CT_ART_42_30', 36)
on conflict (codigo) do nothing;

-- ------------------------------------------------- asignación a cada pilar
update public.permission_types t set category_id = c.id
  from public.permission_categories c
 where c.codigo = 'calamidad_domestica'
   and t.codigo in ('fallecimiento_familiar', 'enfermedad_familiar',
                    'siniestro_domicilio', 'caso_fortuito');

update public.permission_types t set category_id = c.id
  from public.permission_categories c
 where c.codigo = 'cita_medica'
   and t.codigo in ('cita_medica', 'emergencia_medica', 'enfermedad', 'maternidad',
                    'paternidad', 'lactancia', 'cuidado_discapacidad',
                    'donacion_sangre', 'acompanamiento_medico');

update public.permission_types t set category_id = c.id
  from public.permission_categories c
 where c.codigo = 'permiso_personal'
   and t.codigo in ('citacion_judicial', 'tramite_gobierno', 'sufragio',
                    'estudios', 'matrimonio', 'permiso_personal');

-- Ningún subtipo puede quedar huérfano: si alguno no encajó, va a personal.
update public.permission_types t set category_id = c.id
  from public.permission_categories c
 where c.codigo = 'permiso_personal' and t.category_id is null;

-- ------------------------------------------------- guías de redacción
-- Quien decide (jefe y Talento Humano) solo cuenta con lo que el solicitante
-- escriba. Un ejemplo concreto por subtipo evita el clásico «permiso
-- personal» sin más, que obliga a devolver la solicitud y perder un día.

update public.permission_types set
  guia_ejemplo = 'Ej.: Tengo cita de control con el traumatólogo en el Hospital de los Valles, av. Interoceánica. La cita es a las 10:00. Salgo 09:00 y calculo volver a las 12:30 porque voy en transporte público.',
  guia_adjuntos = 'Adjunte la captura o el documento del turno donde se lean la fecha, la hora y el establecimiento.'
where codigo = 'cita_medica';

update public.permission_types set
  guia_ejemplo = 'Ej.: Me descompensé en la oficina con dolor en el pecho y acudí a emergencias del Hospital Metropolitano a las 11:20. Aviso desde la sala de espera e informaré el diagnóstico apenas me atiendan.',
  guia_adjuntos = 'Hoja de atención de emergencia o el certificado que emita el establecimiento. Si aún no lo tiene, entréguelo al reincorporarse.'
where codigo = 'emergencia_medica';

update public.permission_types set
  guia_ejemplo = 'Ej.: El médico del IESS me otorgó reposo por 3 días, del 12 al 14 de marzo, por un cuadro de gastroenteritis. Me reincorporo el 15 a primera hora.',
  guia_adjuntos = 'Certificado de reposo del IESS o del médico tratante, con sello y número de registro profesional.'
where codigo = 'enfermedad';

update public.permission_types set
  guia_ejemplo = 'Ej.: Debo acompañar a mi hijo de 6 años a su control pediátrico en el Centro de Salud de Cotocollao. La cita es a las 08:30 y calculo estar en la oficina a las 11:00.',
  guia_adjuntos = 'Turno de la cita del familiar y un documento que acredite el parentesco.'
where codigo = 'acompanamiento_medico';

update public.permission_types set
  guia_ejemplo = 'Ej.: Mi fecha probable de parto es el 20 de mayo. Solicito las 12 semanas de licencia desde esa fecha. Dejé al día el informe mensual y coordiné el traspaso con mi equipo.',
  guia_adjuntos = 'Certificado médico con la fecha probable de parto. Tras el nacimiento, la partida de nacimiento o el certificado de nacido vivo.'
where codigo = 'maternidad';

update public.permission_types set
  guia_ejemplo = 'Ej.: Mi hija nació el 3 de abril en la Clínica Pichincha. Solicito los días de licencia desde el 4 de abril.',
  guia_adjuntos = 'Certificado de nacido vivo o partida de nacimiento.'
where codigo = 'paternidad';

update public.permission_types set
  guia_ejemplo = 'Ej.: Me reincorporo el 1 de julio y solicito la jornada reducida por lactancia hasta que mi hijo cumpla 12 meses. Entraré a las 08:00 y saldré a las 14:00.',
  guia_adjuntos = 'Partida de nacimiento del menor.'
where codigo = 'lactancia';

update public.permission_types set
  guia_ejemplo = 'Ej.: Mi madre tiene discapacidad del 60% y debo llevarla a su terapia en la av. América. La cita es a las 15:00 y calculo 2 horas.',
  guia_adjuntos = 'Carné de discapacidad del familiar y el turno o cita a la que asistirá.'
where codigo = 'cuidado_discapacidad';

update public.permission_types set
  guia_ejemplo = 'Ej.: Donaré sangre en la Cruz Roja de la av. Gran Colombia por un pedido para mi cuñado, internado en el Eugenio Espejo. Voy a las 09:00 y calculo regresar a las 12:00.',
  guia_adjuntos = 'Comprobante de la donación emitido por la Cruz Roja o el banco de sangre. Puede entregarlo al volver.'
where codigo = 'donacion_sangre';

update public.permission_types set
  guia_ejemplo = 'Ej.: Falleció mi padre el 8 de marzo en Ambato. Viajo hoy para el velorio y el sepelio, y regreso el 11 de marzo.',
  guia_adjuntos = 'Certificado o acta de defunción. Si aún no lo tiene, entréguelo al reincorporarse.'
where codigo = 'fallecimiento_familiar';

update public.permission_types set
  guia_ejemplo = 'Ej.: Mi esposa sufrió un accidente de tránsito y está internada en el Hospital Vozandes. Debo acompañarla hoy y mañana porque no hay otro familiar en la ciudad.',
  guia_adjuntos = 'Hoja de atención, certificado del hospital o parte policial del accidente.'
where codigo = 'enfermedad_familiar';

update public.permission_types set
  guia_ejemplo = 'Ej.: Se rompió la tubería matriz y se inundó mi departamento en Carcelén. Debo estar presente para el plomero y el peritaje del seguro. Calculo el día completo.',
  guia_adjuntos = 'Fotografías del daño y, según el caso, parte de bomberos, denuncia o informe del seguro.'
where codigo = 'siniestro_domicilio';

update public.permission_types set
  guia_ejemplo = 'Ej.: Un deslave cerró la vía a Nono desde las 06:00 y no hay paso vehicular. Estoy retenido en el km 12 y adjunto la publicación del ECU-911. Llegaré apenas se habilite la vía.',
  guia_adjuntos = 'Cualquier constancia del hecho: publicación oficial, parte policial o fotografía con fecha.'
where codigo = 'caso_fortuito';

update public.permission_types set
  guia_ejemplo = 'Ej.: Tengo citación de la Agencia Nacional de Tránsito para impugnar una multa que considero sin fundamento. La diligencia es a las 10:00 en la agencia de la av. Occidental. Voy en transporte público, así que calculo entre 1 y 2 horas fuera de la oficina.',
  guia_adjuntos = 'La boleta de citación o notificación, y el documento del caso: la multa, el expediente o las fotografías que respalden su posición.'
where codigo = 'citacion_judicial';

update public.permission_types set
  guia_ejemplo = 'Ej.: Debo renovar mi cédula en el Registro Civil del CCI. El turno es a las 08:00 del martes 5 y es el único disponible este mes. Calculo 2 horas.',
  guia_adjuntos = 'El turno o la cita agendada, donde se lean la fecha, la hora y la institución.'
where codigo = 'tramite_gobierno';

update public.permission_types set
  guia_ejemplo = 'Ej.: Soy miembro de la junta receptora del voto en el recinto Colegio Mejía para las elecciones del 9 de febrero.',
  guia_adjuntos = 'Notificación como miembro de junta o certificado de votación. Puede entregarlo después.'
where codigo = 'sufragio';

update public.permission_types set
  guia_ejemplo = 'Ej.: Rindo el examen final de la maestría en la PUCE el jueves 12, de 18:00 a 20:00, y necesito salir a las 17:00. Es la única fecha: la supletoria es en dos meses.',
  guia_adjuntos = 'Calendario académico, convocatoria al examen o certificado de la institución.'
where codigo = 'estudios';

update public.permission_types set
  guia_ejemplo = 'Ej.: Me caso el 14 de junio en el Registro Civil de la av. Amazonas, a las 11:00. Solicito ese día y los dos siguientes.',
  guia_adjuntos = 'Certificado de matrimonio o la constancia del turno en el Registro Civil.'
where codigo = 'matrimonio';

update public.permission_types set
  guia_ejemplo = 'Ej.: Necesito la mañana del viernes 7 para un asunto familiar en Sangolquí. Entiendo que se descuenta de mi saldo de vacaciones. Regreso a las 14:00.',
  guia_adjuntos = 'No exige respaldo, pero adjunte lo que ayude a su jefe a dimensionar la urgencia.'
where codigo = 'permiso_personal';

-- El antiguo tipo genérico «Calamidad doméstica» pasó a ser un pilar. No se
-- elimina —hay solicitudes que lo referencian y la bitácora es inmutable—:
-- se convierte en el subtipo de respaldo para lo que no encaje en los otros.
update public.permission_types set
  nombre = 'Otra calamidad doméstica',
  descripcion = 'Hecho grave e imprevisto del hogar que no encaja en los anteriores',
  orden = 39,
  guia_ejemplo = 'Ej.: Mi hija de 8 años se quedó sola porque la persona que la cuida sufrió una emergencia y debo retirarla de la escuela en La Floresta a las 13:00. No tengo con quién dejarla el resto de la tarde.',
  guia_adjuntos = 'Adjunte lo que documente el hecho. Si no existe documento, explique con el mayor detalle posible: es lo único con lo que contará quien decida.'
where codigo = 'calamidad_domestica';

update public.permission_types t set category_id = c.id
  from public.permission_categories c
 where c.codigo = 'calamidad_domestica' and t.codigo = 'calamidad_domestica';

-- Orden dentro de cada pilar: de lo más frecuente a lo más excepcional, y el
-- subtipo de respaldo siempre al final.
update public.permission_types set orden = 31 where codigo = 'fallecimiento_familiar';
update public.permission_types set orden = 32 where codigo = 'enfermedad_familiar';
update public.permission_types set orden = 33 where codigo = 'siniestro_domicilio';
update public.permission_types set orden = 34 where codigo = 'caso_fortuito';
update public.permission_types set orden = 39 where codigo = 'calamidad_domestica';

-- =========================================================================
-- C. Bloque mínimo de vacaciones
--
-- Regla de la empresa: las vacaciones se toman en bloques de al menos 7 días
-- calendario. Pedir menos deja de ser un trámite ordinario y pasa a ser una
-- excepción: exige documento y justificación, y se decide en orden inverso
-- —primero Talento Humano, después el jefe inmediato—, porque quien autoriza
-- apartarse de la política es Talento Humano, no la jefatura.
-- =========================================================================

insert into public.app_config (clave, valor, descripcion) values
  ('vacaciones_bloque_minimo', '7',
   'Días calendario mínimos por solicitud de vacaciones. Menos exige justificación documentada y lo autoriza primero Talento Humano.')
on conflict (clave) do update set descripcion = excluded.descripcion;

insert into public.app_config (clave, valor, descripcion) values
  ('mandato_descripcion',
   'Declare toda la información pertinente: el motivo, el lugar, la hora y cuánto tiempo estará ausente. Su jefe inmediato y Talento Humano deciden únicamente con lo que usted escriba aquí y con lo que adjunte. Si falta un dato, la solicitud se devuelve y usted pierde el tiempo que quería ganar.',
   'Texto que encabeza el campo de descripción en toda solicitud')
on conflict (clave) do update set valor = excluded.valor, descripcion = excluded.descripcion;

alter table public.requests
  add column if not exists ruta_aprobacion text not null default 'estandar';

alter table public.requests
  add column if not exists bloque_menor_justificado boolean not null default false;

do $ruta$
begin
  if not exists (select 1 from pg_constraint where conname = 'requests_ruta_aprobacion_valida') then
    alter table public.requests add constraint requests_ruta_aprobacion_valida
      check (ruta_aprobacion in ('estandar', 'rrhh_primero'));
  end if;
end
$ruta$;

comment on column public.requests.ruta_aprobacion is
  'estandar: jefe y luego Talento Humano. rrhh_primero: excepción a una regla de política, la autoriza Talento Humano antes que la jefatura.';

-- =========================================================================
-- D. Ajustes de Talento Humano sobre lo ya otorgado
--
-- Caso real: se autoriza un permiso de 2 horas por cita médica y de ahí sale
-- un reposo de 3 días. Hasta ahora el sistema solo conocía el permiso
-- original: garita seguía esperando a la persona y el jefe la daba por
-- presente. Talento Humano puede ahora extender o reducir la ausencia,
-- dejando constancia de por qué.
--
-- No se pisa el historial: la solicitud conserva sus fechas originales en
-- esta tabla, y cada ajuste queda con autor, momento y justificación.
-- =========================================================================

create table if not exists public.request_adjustments (
  id                bigint generated by default as identity primary key,
  request_id        uuid not null references public.requests(id) on delete cascade,
  fecha_inicio_ant  date not null,
  fecha_fin_ant     date not null,
  fecha_inicio_nueva date not null,
  fecha_fin_nueva   date not null,
  dias_ant          numeric(6,2) not null,
  dias_nuevos       numeric(6,2) not null,
  motivo            text not null,
  resolucion        text not null,
  ajustado_por      uuid not null references public.users(id),
  created_at        timestamptz not null default now(),
  constraint request_adjustments_rango_valido check (fecha_fin_nueva >= fecha_inicio_nueva),
  constraint request_adjustments_motivo_util check (length(btrim(motivo)) >= 15),
  constraint request_adjustments_resolucion_util check (length(btrim(resolucion)) >= 15)
);

comment on table public.request_adjustments is
  'Extensiones y correcciones que Talento Humano aplica a una ausencia ya autorizada. Inmutable: solo se inserta.';

create index if not exists request_adjustments_request_idx
  on public.request_adjustments (request_id, created_at desc);

alter table public.request_adjustments enable row level security;

-- El interesado ve los ajustes de sus propias ausencias; Talento Humano y el
-- jefe inmediato, los de quienes deben cubrir. Nadie puede editarlos.
drop policy if exists request_adjustments_lectura on public.request_adjustments;
create policy request_adjustments_lectura on public.request_adjustments
  for select to authenticated using (
    is_rrhh_o_admin()
    or exists (
      select 1 from public.requests r
       where r.id = request_adjustments.request_id
         and (r.user_id = auth.uid() or r.jefe_id = auth.uid())
    )
  );

drop policy if exists request_adjustments_sin_edicion on public.request_adjustments;
create policy request_adjustments_sin_edicion on public.request_adjustments
  for update to authenticated using (false);

-- Marca en la solicitud para que garita, informes y calendario distingan una
-- ausencia ajustada de una original sin tener que cruzar tablas.
-- `on delete set null` como el resto de columnas de «quién decidió»
-- (jefe_aprobado_por, rrhh_aprobado_por): si algún día se depura a una
-- persona, la ausencia no puede desaparecer con ella. La constancia
-- detallada del ajuste vive en `request_adjustments`, que sí la retiene.
alter table public.requests add column if not exists ajustada_en timestamptz;
alter table public.requests
  add column if not exists ajustada_por uuid references public.users(id) on delete set null;

do $fk$
begin
  if exists (select 1 from pg_constraint
              where conname = 'requests_ajustada_por_fkey' and confdeltype = 'a') then
    alter table public.requests drop constraint requests_ajustada_por_fkey;
    alter table public.requests add constraint requests_ajustada_por_fkey
      foreign key (ajustada_por) references public.users(id) on delete set null;
  end if;
end
$fk$;

-- ------------------------------------------------- aplicación del ajuste
-- Todo en una función para que el saldo, las fechas y la constancia se
-- muevan juntos o no se muevan: si el ajuste sobre una vacación cambia los
-- días, hay que devolver los anteriores y descontar los nuevos, y eso no
-- puede quedar a medias.
create or replace function public.ajustar_ausencia(
  p_request_id uuid,
  p_inicio     date,
  p_fin        date,
  p_motivo     text,
  p_resolucion text,
  p_por        uuid
) returns public.requests
language plpgsql
security definer
set search_path = public
as $ajuste$
declare
  v_sol    public.requests;
  v_dias   numeric(6,2);
  v_fds    integer;
begin
  select * into v_sol from public.requests where id = p_request_id for update;
  if not found then
    raise exception 'La solicitud no existe';
  end if;

  if v_sol.estado <> 'aprobado' then
    raise exception 'Solo se ajusta una ausencia ya aprobada (esta está en %)', v_sol.estado;
  end if;

  if p_fin < p_inicio then
    raise exception 'La fecha de fin no puede ser anterior a la de inicio';
  end if;

  if length(btrim(coalesce(p_motivo, ''))) < 15 or length(btrim(coalesce(p_resolucion, ''))) < 15 then
    raise exception 'El ajuste exige explicar el caso y la resolución (mínimo 15 caracteres cada uno)';
  end if;

  v_dias := public.calcular_dias(v_sol.tipo, p_inicio, p_fin);

  -- El saldo solo se mueve en vacaciones; un permiso remunerado no lo toca.
  if v_sol.tipo = 'vacacion' and v_dias <> v_sol.dias_solicitados then
    perform public.reversar_vacaciones(v_sol.user_id, v_sol.dias_solicitados,
                                       v_sol.id, v_sol.fines_semana);
    v_fds := v_sol.fines_semana;
    perform public.consumir_vacaciones(v_sol.user_id, v_dias, v_sol.id, v_fds, p_por);
  end if;

  insert into public.request_adjustments
    (request_id, fecha_inicio_ant, fecha_fin_ant, fecha_inicio_nueva, fecha_fin_nueva,
     dias_ant, dias_nuevos, motivo, resolucion, ajustado_por)
  values
    (v_sol.id, v_sol.fecha_inicio, v_sol.fecha_fin, p_inicio, p_fin,
     v_sol.dias_solicitados, v_dias, btrim(p_motivo), btrim(p_resolucion), p_por);

  update public.requests set
    fecha_inicio = p_inicio,
    fecha_fin = p_fin,
    dias_solicitados = v_dias,
    ajustada_en = now(),
    ajustada_por = p_por,
    updated_at = now()
  where id = v_sol.id
  returning * into v_sol;

  return v_sol;
end
$ajuste$;

revoke all on function public.ajustar_ausencia(uuid, date, date, text, text, uuid) from public;

-- =========================================================================
-- E. Calendario de jefatura
--
-- El jefe necesita ver a su equipo mes a mes para no quedarse sin nadie. Se
-- añade lo que le sirve para planificar —si es media jornada o la semana
-- entera, quién cubre, si Talento Humano ya lo ajustó— y se sigue omitiendo
-- el motivo detallado: el subtipo de un permiso médico es dato de salud
-- (LOPDP Art. 4). El jefe lo ve en la solicitud que él mismo autoriza, que
-- es donde corresponde, no en una grilla mensual a la vista de todos.
-- =========================================================================

-- Se recrea en vez de reemplazarse: se añaden columnas en medio (cargo,
-- horas, tipo) y PostgreSQL no permite renombrar columnas con
-- `create or replace view`.
drop view if exists public.v_calendario_equipo;

create view public.v_calendario_equipo as
select r.id            as request_id,
       r.folio,
       u.id            as user_id,
       u.nombre,
       u.cargo,
       u.departamento,
       u.jefe_id,
       r.fecha_inicio,
       r.fecha_fin,
       r.hora_inicio,
       r.hora_fin,
       r.dias_solicitados,
       r.estado,
       r.tipo,
       case r.tipo when 'vacacion' then 'Vacaciones' else 'Permiso' end as motivo_general,
       r.reemplazo_id,
       s.nombre        as reemplazo_nombre,
       r.ajustada_en
  from public.requests r
  join public.users u on u.id = r.user_id
  left join public.users s on s.id = r.reemplazo_id
 where r.estado in ('pendiente_jefe', 'pendiente_rrhh', 'pendiente_anulacion', 'aprobado')
   and r.fecha_fin >= current_date - 31;

comment on view public.v_calendario_equipo is
  'Ausencias vigentes para planificar cobertura. Nunca expone el subtipo del permiso: es dato de salud bajo LOPDP Art. 4.';

grant select on public.v_calendario_equipo to authenticated;

-- Catálogo que consume el formulario: pilar, subtipos y guías en una consulta.
create or replace view public.v_catalogo_permisos as
select c.id          as categoria_id,
       c.codigo      as categoria_codigo,
       c.nombre      as categoria_nombre,
       c.descripcion as categoria_descripcion,
       c.ayuda       as categoria_ayuda,
       c.orden       as categoria_orden,
       t.id          as tipo_id,
       t.codigo      as tipo_codigo,
       t.nombre      as tipo_nombre,
       t.descripcion as tipo_descripcion,
       t.requiere_adjunto,
       t.requiere_justificacion,
       t.remunerado,
       t.descuenta_vacaciones,
       t.max_dias,
       t.max_horas,
       t.legal_ref,
       t.guia_ejemplo,
       t.guia_adjuntos,
       t.orden       as tipo_orden
  from public.permission_categories c
  join public.permission_types t on t.category_id = c.id
 where c.activo and t.activo;

grant select on public.v_catalogo_permisos to authenticated;

-- =========================================================================
-- F. El bloque mínimo se hace cumplir en la base
--
-- Se valida aquí y no solo en el formulario: la API es la misma para el
-- navegador, para un script y para cualquier integración futura. Una regla
-- de negocio que solo vive en el frontend no es una regla, es una sugerencia.
--
-- La comprobación es diferida (al COMMIT) porque el respaldo de la excepción
-- —los adjuntos— se inserta después de la fila de la solicitud.
-- =========================================================================

create or replace function public.tg_requests_validar_requisitos()
returns trigger
language plpgsql
as $req$
declare
  v_pt        public.permission_types%rowtype;
  v_adjuntos  int;
  v_firmas    int;
  v_minimo    numeric;
begin
  -- Se ejecuta al COMMIT: la solicitud pudo eliminarse en la misma
  -- transacción (o por cascada). En ese caso no hay nada que validar.
  if not exists (select 1 from public.requests where id = new.id) then
    return null;
  end if;

  select count(*) into v_adjuntos from public.request_attachments where request_id = new.id;
  select count(*) into v_firmas   from public.request_signatures
    where request_id = new.id and rol_firma = 'solicitante';

  if new.tipo = 'permiso' then
    select * into v_pt from public.permission_types where id = new.permission_type_id;

    if v_pt.requiere_adjunto and v_adjuntos = 0 then
      raise exception 'El permiso "%" exige adjuntar el respaldo (certificado, cita o documento)', v_pt.nombre;
    end if;

    if v_pt.requiere_firma and v_firmas = 0 then
      raise exception 'El permiso "%" exige la firma electrónica del solicitante', v_pt.nombre;
    end if;
  end if;

  if new.tipo = 'vacacion' then
    select coalesce(nullif(valor, '')::numeric, 0) into v_minimo
      from public.app_config where clave = 'vacaciones_bloque_minimo';
    v_minimo := coalesce(v_minimo, 0);

    -- El mínimo y la justificación se comprueban al insertar (ver
    -- `tg_requests_ruta_aprobacion`), que devuelve el error de inmediato.
    -- Aquí solo queda el adjunto, que llega después de la fila.
    if v_minimo > 0 and ((new.fecha_fin - new.fecha_inicio) + 1) < v_minimo then
      if v_adjuntos = 0 then
        raise exception
          'Para tomar menos de % días debe adjuntar el documento que respalde la excepción.',
          v_minimo;
      end if;
    end if;
  end if;

  return null;
end;
$req$;

-- ------------------------------------------------- ruta de aprobación
-- Se decide en la base, no en el cliente: un formulario alterado no puede
-- elegir por dónde pasa su solicitud. Corre después de
-- `requests_before_insert` —los disparadores se ejecutan en orden
-- alfabético— que es quien fija el estado inicial.
create or replace function public.tg_requests_ruta_aprobacion()
returns trigger
language plpgsql
as $ruta$
declare
  v_minimo     numeric;
  v_calendario integer;
begin
  new.ruta_aprobacion := 'estandar';

  if new.tipo = 'vacacion' then
    select coalesce(nullif(valor, '')::numeric, 0) into v_minimo
      from public.app_config where clave = 'vacaciones_bloque_minimo';

    -- El mínimo se mide en días de AUSENCIA, no en los que se descuentan del
    -- saldo. Un feriado dentro del rango no acorta el descanso: la persona
    -- igual está fuera. Medirlo contra `dias_solicitados` —que excluye
    -- feriados— hacía imposible tomar la semana de Navidad o de Carnaval.
    v_calendario := (new.fecha_fin - new.fecha_inicio) + 1;

    if coalesce(v_minimo, 0) > 0 and v_calendario < v_minimo then
      if not new.bloque_menor_justificado then
        raise exception
          'Las vacaciones se toman en bloques de al menos % días seguidos y usted pidió %. Si su caso lo amerita, márquelo como excepción, explique el motivo y adjunte el respaldo: la autoriza Talento Humano, no su jefe.',
          v_minimo, v_calendario
          using errcode = 'P0001', hint = 'bloque_minimo|' || v_minimo::text;
      end if;

      if length(btrim(coalesce(new.justificacion, ''))) < 30 then
        raise exception
          'Para tomar menos de % días debe justificarlo por escrito, con al menos 30 caracteres: quien autoriza la excepción necesita entender por qué se aparta de la política.',
          v_minimo;
      end if;

      -- Apartarse de la política no lo autoriza la jefatura sino Talento
      -- Humano. Recién con su visto bueno pasa al jefe, que evalúa la
      -- cobertura del puesto.
      new.ruta_aprobacion := 'rrhh_primero';
      new.estado := 'pendiente_rrhh';
    end if;
  else
    new.bloque_menor_justificado := false;
  end if;

  return new;
end;
$ruta$;

drop trigger if exists requests_ruta_aprobacion on public.requests;
create trigger requests_ruta_aprobacion
  before insert on public.requests
  for each row execute function public.tg_requests_ruta_aprobacion();

-- ------------------------------------------------- excepción para el ajuste
-- Se reescribe entero el disparador porque PL/pgSQL no permite parchear un
-- cuerpo existente. Salvo la condición señalada más abajo, es idéntico al
-- de la migración 0006: validación de transiciones, emisión del QR, consumo
-- y devolución del saldo, y resolución de anulaciones.
create or replace function public.tg_requests_before_update()
returns trigger
language plpgsql
as $upd$
declare
  v_descuenta boolean := false;
begin
  if (new.fecha_inicio, new.fecha_fin, new.tipo) is distinct from (old.fecha_inicio, old.fecha_fin, old.tipo) then
    -- Una ausencia aprobada no se corrige a mano: la única vía es
    -- `ajustar_ausencia()`, que deja constancia de quién, cuándo y por qué.
    -- La puerta es un indicador de transacción que solo esa función levanta;
    -- no se usa `ajustada_en` como señal porque un UPDATE directo podría
    -- fijarlo, mientras que este indicador no existe fuera de la función.
    if old.estado <> 'pendiente_jefe'
       and coalesce(current_setting('app.ajuste_en_curso', true), '') <> '1' then
      raise exception 'No se pueden modificar las fechas de una solicitud en estado %', old.estado;
    end if;
    new.dias_solicitados := public.calcular_dias(new.tipo, new.fecha_inicio, new.fecha_fin);
    new.fines_semana     := public.fines_de_semana_completos(new.fecha_inicio, new.fecha_fin);
  end if;

  if new.estado is distinct from old.estado then
    if not (
         (old.estado = 'pendiente_jefe'      and new.estado in ('pendiente_rrhh', 'rechazado', 'cancelado'))
      -- Cierre de la ruta invertida: el jefe es el segundo y último en
      -- decidir, así que su visto bueno deja la solicitud aprobada.
      or (old.estado = 'pendiente_jefe'      and new.estado = 'aprobado'
          and new.ruta_aprobacion = 'rrhh_primero' and new.rrhh_aprobado_por is not null)
      or (old.estado = 'pendiente_rrhh'      and new.estado in ('aprobado', 'rechazado', 'cancelado'))
      -- Ruta invertida: Talento Humano autorizó la excepción al bloque
      -- mínimo y ahora le toca al jefe confirmar la cobertura del puesto.
      or (old.estado = 'pendiente_rrhh'      and new.estado = 'pendiente_jefe'
          and new.ruta_aprobacion = 'rrhh_primero')
      -- Anular algo aprobado pasa por Talento Humano; cancelarlo directo queda
      -- reservado a RRHH, que es quien responde por el saldo y por el QR emitido.
      or (old.estado = 'aprobado'            and new.estado in ('pendiente_anulacion', 'cancelado'))
      or (old.estado = 'pendiente_anulacion' and new.estado in ('cancelado', 'aprobado'))
    ) then
      raise exception 'Transición de estado inválida: % -> %', old.estado, new.estado;
    end if;

    if new.estado = 'pendiente_rrhh' then
      new.jefe_aprobado_en := coalesce(new.jefe_aprobado_en, now());
    end if;

    -- Ruta invertida: el paso a manos del jefe significa que Talento Humano
    -- ya resolvió. Sin esta marca, su decisión no quedaba fechada.
    if new.estado = 'pendiente_jefe' and old.estado = 'pendiente_rrhh' then
      new.rrhh_aprobado_en := coalesce(new.rrhh_aprobado_en, now());
    end if;

    if new.estado = 'rechazado' then
      new.rechazado_en := coalesce(new.rechazado_en, now());
    end if;

    if new.estado = 'pendiente_anulacion' then
      new.anulacion_solicitada_en := coalesce(new.anulacion_solicitada_en, now());
    end if;

    -- Anulación denegada: la solicitud vuelve a estar vigente
    if new.estado = 'aprobado' and old.estado = 'pendiente_anulacion' then
      new.anulacion_resuelta_en := coalesce(new.anulacion_resuelta_en, now());
      return new;                      -- el saldo no se tocó, no hay nada que revertir
    end if;

    if new.tipo = 'vacacion' then
      v_descuenta := true;
    else
      select coalesce(descuenta_vacaciones, false) into v_descuenta
      from public.permission_types where id = new.permission_type_id;
    end if;

    if new.estado = 'aprobado' then
      new.rrhh_aprobado_en := coalesce(new.rrhh_aprobado_en, now());
      new.qr_hash          := coalesce(new.qr_hash, gen_random_uuid());
      new.qr_emitido_en    := coalesce(new.qr_emitido_en, now());
      new.qr_expira_en     := coalesce(new.qr_expira_en, (new.fecha_fin + 1)::timestamptz);

      if v_descuenta then
        perform public.consumir_vacaciones(
          new.user_id, new.dias_solicitados, new.id, new.fines_semana, new.rrhh_aprobado_por);
      end if;
    end if;

    -- Se devuelve el saldo al cancelar, venga de una aprobada o de una anulación
    if new.estado = 'cancelado' and old.estado in ('aprobado', 'pendiente_anulacion') and v_descuenta then
      perform public.reversar_vacaciones(
        new.user_id, new.dias_solicitados, new.id, new.fines_semana);
      new.anulacion_resuelta_en := coalesce(new.anulacion_resuelta_en, now());
      -- Un QR anulado deja de servir en garita
      new.qr_expira_en := now();
    end if;
  end if;

  return new;
end;
$upd$;

-- La función de ajuste levanta el indicador, acotado a su transacción.
create or replace function public.ajustar_ausencia(
  p_request_id uuid,
  p_inicio     date,
  p_fin        date,
  p_motivo     text,
  p_resolucion text,
  p_por        uuid
) returns public.requests
language plpgsql
security definer
set search_path = public
as $ajuste$
declare
  v_sol  public.requests;
  v_dias numeric(6,2);
begin
  select * into v_sol from public.requests where id = p_request_id for update;
  if not found then
    raise exception 'La solicitud no existe';
  end if;

  if v_sol.estado <> 'aprobado' then
    raise exception 'Solo se ajusta una ausencia ya aprobada (esta está en %)', v_sol.estado;
  end if;

  if p_fin < p_inicio then
    raise exception 'La fecha de fin no puede ser anterior a la de inicio';
  end if;

  if length(btrim(coalesce(p_motivo, ''))) < 15 or length(btrim(coalesce(p_resolucion, ''))) < 15 then
    raise exception 'El ajuste exige explicar el caso y la resolución (mínimo 15 caracteres cada uno)';
  end if;

  v_dias := public.calcular_dias(v_sol.tipo, p_inicio, p_fin);

  -- El saldo solo se mueve en vacaciones; un permiso remunerado no lo toca.
  if v_sol.tipo = 'vacacion' and v_dias <> v_sol.dias_solicitados then
    perform public.reversar_vacaciones(v_sol.user_id, v_sol.dias_solicitados,
                                       v_sol.id, v_sol.fines_semana);
    perform public.consumir_vacaciones(v_sol.user_id, v_dias, v_sol.id,
                                       v_sol.fines_semana, p_por);
  end if;

  insert into public.request_adjustments
    (request_id, fecha_inicio_ant, fecha_fin_ant, fecha_inicio_nueva, fecha_fin_nueva,
     dias_ant, dias_nuevos, motivo, resolucion, ajustado_por)
  values
    (v_sol.id, v_sol.fecha_inicio, v_sol.fecha_fin, p_inicio, p_fin,
     v_sol.dias_solicitados, v_dias, btrim(p_motivo), btrim(p_resolucion), p_por);

  -- `true`: vive solo dentro de esta transacción.
  perform set_config('app.ajuste_en_curso', '1', true);

  update public.requests set
    fecha_inicio = p_inicio,
    fecha_fin    = p_fin,
    qr_expira_en = (p_fin + 1)::timestamptz,   -- garita debe reconocer el nuevo fin
    ajustada_en  = now(),
    ajustada_por = p_por,
    updated_at   = now()
  where id = v_sol.id
  returning * into v_sol;

  perform set_config('app.ajuste_en_curso', '0', true);
  return v_sol;
end
$ajuste$;

revoke all on function public.ajustar_ausencia(uuid, date, date, text, text, uuid) from public;
